export { default as Home } from './Home/Home'
export { default as About } from './About/About'
export { default as Loading } from './Loading/Loading'
export { default as Addons } from './Addons/Addons'
export { default as HowTo } from './HowTo/HowTo'
